import type { Metadata } from "next";
import "@public/assets/globals.css";
import { Navbar, Footer } from "@/components/Common/";
import { UIProvider } from "@/contexts/ui";
import { Quicksand, Jost } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

const jost = Jost({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-jost",
});
const qs = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-qs",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${jost.variable}  
        ${qs.variable}`}
      >
        <UIProvider>
          <Navbar background="bg-white" />
          <div className="pt-20 md:pt-24 min-h-screen antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900">
            {children}
          </div>
          <Footer />
        </UIProvider>
        <Toaster
          position="top-center"
          richColors
        // closeButton 
        />
      </body>
    </html>
  );
}
