import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@public/assets/globals.css";
import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import { UIProvider } from "@/contexts/ui";
import { Quicksand, DM_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const dmsans = DM_Sans({
    weight: ['300','400','500','600','700','800','900','1000'],
    subsets: ['latin'],
    variable: '--font-dmsans',
})
const qs = Quicksand({
    weight: ['300','400','500','600','700'],
    subsets: ['latin'],
    variable: '--font-qs',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
        ${dmsans.variable}  
        ${qs.variable}`}
      >
        <UIProvider>
          <Navbar background="bg-white" />
            <div className="pt-24 min-h-screen bg-white dark:bg-black dark:text-white">{children}</div>
          <Footer />
        </UIProvider>
      </body>
    </html>
  );
}
